language: node_js   #运行环境为nodejs
node_js:            #设置版本号
  - "6"
cache: npm

notifications:      #通知
  email:
    recipients:
      - 215586821@qq.com   #设置通知邮件
    on_success: change
    on_failure: always


install:                             #install阶段 安装依赖
  - npm install -g gitbook-cli       #安装gitbook 
  - gitbook install                  #安装插件
  - npm install -g gitbook-summary   #使自动生成SUMMARY.md的一个工具

script:                              #script阶段 运行脚本
  - book sm                          #利用安装的工具gitbook-summary自动生成SUMMARY.md文件
  - gitbook build                    #gitbook编译，生成静态网站站点_book
  

after_script:                        #script阶段之后执行 
  - cd _book                         #进入_book目录
  - git init          
  - git config user.name "hanyanjun"
  - git config user.email "HYJ_hanyanjun@163.com"               
  - git remote add origin https://github.com/hanyanjun/gitbook.git    #设置要托管到的仓库名
  - git add .                               #添加_book目录下的所有文件
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages" 
  - git branch -M master
  - git push --force --quiet "https://a5ac11bd06286281e2c68d634dd0d5b7e0099ab0@github.com/hanyanjun/gitbook.git" master:gh-pages  #强制推送到gh-pages分支

branches:
  only:
    - master

env:
  global:
    - REF=github.com/hanyanjun/gitbook.git # 设置 github 地址 token : a5ac11bd06286281e2c68d634dd0d5b7e0099ab0